### ISSUE TITLE
No longer working in 2021.1.0a6

### ISSUE THREAD

**Issue by SugoiDev** [Unity-Technologies/com.unity.performance-tracking#4]
No longer working in 2021.1.0a6

```
Library\PackageCache\com.unity.performance-tracking@2520acd5c4\Editor\ProfilerHelpers.cs(467,56): error CS0246: The type or namespace name 'CPUorGPUProfilerModule' could not be found (are you missing a using directive or an assembly reference?)
```

```
Library\PackageCache\com.unity.performance-tracking@2520acd5c4\Editor\ProfilerHelpers.cs(468,46): error CS1061: 'ProfilerFrameDataHierarchyView' does not contain a definition for 'SetSelectionFromLegacyPropertyPath' and no accessible extension method 'SetSelectionFromLegacyPropertyPath' accepting a first argument of type 'ProfilerFrameDataHierarchyView' could be found (are you missing a using directive or an assembly reference?)
```

**Comment by jschmidt42** [comment]
On it

**Comment by jschmidt42** [comment]
Wil get fixed with https://github.com/Unity-Technologies/com.unity.performance-tracking/pull/5
